package com.thinkjoy.report.entity;

import java.io.Serializable;

public class ZgkUniversityEnrollingAlgorithm implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zgk_university_enrolling_algorithm.id
     *
     * @mbggenerated Tue Feb 07 14:28:33 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zgk_university_enrolling_algorithm.university_id
     *
     * @mbggenerated Tue Feb 07 14:28:33 CST 2017
     */
    private Integer universityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zgk_university_enrolling_algorithm.enroll_area
     *
     * @mbggenerated Tue Feb 07 14:28:33 CST 2017
     */
    private String enrollArea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zgk_university_enrolling_algorithm.enroll_year
     *
     * @mbggenerated Tue Feb 07 14:28:33 CST 2017
     */
    private Integer enrollYear;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zgk_university_enrolling_algorithm.enroll_batch
     *
     * @mbggenerated Tue Feb 07 14:28:33 CST 2017
     */
    private String enrollBatch;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zgk_university_enrolling_algorithm.major_type
     *
     * @mbggenerated Tue Feb 07 14:28:33 CST 2017
     */
    private String majorType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zgk_university_enrolling_algorithm.real_enrolled
     *
     * @mbggenerated Tue Feb 07 14:28:33 CST 2017
     */
    private String realEnrolled;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zgk_university_enrolling_algorithm.high_score
     *
     * @mbggenerated Tue Feb 07 14:28:33 CST 2017
     */
    private String highScore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zgk_university_enrolling_algorithm.high_rank
     *
     * @mbggenerated Tue Feb 07 14:28:33 CST 2017
     */
    private Integer highRank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zgk_university_enrolling_algorithm.low_score
     *
     * @mbggenerated Tue Feb 07 14:28:33 CST 2017
     */
    private String lowScore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zgk_university_enrolling_algorithm.low_rank
     *
     * @mbggenerated Tue Feb 07 14:28:33 CST 2017
     */
    private Integer lowRank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zgk_university_enrolling_algorithm.avg_score
     *
     * @mbggenerated Tue Feb 07 14:28:33 CST 2017
     */
    private String avgScore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zgk_university_enrolling_algorithm.avg_rank
     *
     * @mbggenerated Tue Feb 07 14:28:33 CST 2017
     */
    private Integer avgRank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zgk_university_enrolling_algorithm.plan_enroll
     *
     * @mbggenerated Tue Feb 07 14:28:33 CST 2017
     */
    private Integer planEnroll;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zgk_university_enrolling_algorithm.std_high_rank
     *
     * @mbggenerated Tue Feb 07 14:28:33 CST 2017
     */
    private Integer stdHighRank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zgk_university_enrolling_algorithm.std_low_rank
     *
     * @mbggenerated Tue Feb 07 14:28:33 CST 2017
     */
    private Integer stdLowRank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zgk_university_enrolling_algorithm.std_avg_rank
     *
     * @mbggenerated Tue Feb 07 14:28:33 CST 2017
     */
    private Integer stdAvgRank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table zgk_university_enrolling_algorithm
     *
     * @mbggenerated Tue Feb 07 14:28:33 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zgk_university_enrolling_algorithm.id
     *
     * @return the value of zgk_university_enrolling_algorithm.id
     *
     * @mbggenerated Tue Feb 07 14:28:33 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zgk_university_enrolling_algorithm.id
     *
     * @param id the value for zgk_university_enrolling_algorithm.id
     *
     * @mbggenerated Tue Feb 07 14:28:33 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zgk_university_enrolling_algorithm.university_id
     *
     * @return the value of zgk_university_enrolling_algorithm.university_id
     *
     * @mbggenerated Tue Feb 07 14:28:33 CST 2017
     */
    public Integer getUniversityId() {
        return universityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zgk_university_enrolling_algorithm.university_id
     *
     * @param universityId the value for zgk_university_enrolling_algorithm.university_id
     *
     * @mbggenerated Tue Feb 07 14:28:33 CST 2017
     */
    public void setUniversityId(Integer universityId) {
        this.universityId = universityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zgk_university_enrolling_algorithm.enroll_area
     *
     * @return the value of zgk_university_enrolling_algorithm.enroll_area
     *
     * @mbggenerated Tue Feb 07 14:28:33 CST 2017
     */
    public String getEnrollArea() {
        return enrollArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zgk_university_enrolling_algorithm.enroll_area
     *
     * @param enrollArea the value for zgk_university_enrolling_algorithm.enroll_area
     *
     * @mbggenerated Tue Feb 07 14:28:33 CST 2017
     */
    public void setEnrollArea(String enrollArea) {
        this.enrollArea = enrollArea == null ? null : enrollArea.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zgk_university_enrolling_algorithm.enroll_year
     *
     * @return the value of zgk_university_enrolling_algorithm.enroll_year
     *
     * @mbggenerated Tue Feb 07 14:28:33 CST 2017
     */
    public Integer getEnrollYear() {
        return enrollYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zgk_university_enrolling_algorithm.enroll_year
     *
     * @param enrollYear the value for zgk_university_enrolling_algorithm.enroll_year
     *
     * @mbggenerated Tue Feb 07 14:28:33 CST 2017
     */
    public void setEnrollYear(Integer enrollYear) {
        this.enrollYear = enrollYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zgk_university_enrolling_algorithm.enroll_batch
     *
     * @return the value of zgk_university_enrolling_algorithm.enroll_batch
     *
     * @mbggenerated Tue Feb 07 14:28:33 CST 2017
     */
    public String getEnrollBatch() {
        return enrollBatch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zgk_university_enrolling_algorithm.enroll_batch
     *
     * @param enrollBatch the value for zgk_university_enrolling_algorithm.enroll_batch
     *
     * @mbggenerated Tue Feb 07 14:28:33 CST 2017
     */
    public void setEnrollBatch(String enrollBatch) {
        this.enrollBatch = enrollBatch == null ? null : enrollBatch.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zgk_university_enrolling_algorithm.major_type
     *
     * @return the value of zgk_university_enrolling_algorithm.major_type
     *
     * @mbggenerated Tue Feb 07 14:28:33 CST 2017
     */
    public String getMajorType() {
        return majorType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zgk_university_enrolling_algorithm.major_type
     *
     * @param majorType the value for zgk_university_enrolling_algorithm.major_type
     *
     * @mbggenerated Tue Feb 07 14:28:33 CST 2017
     */
    public void setMajorType(String majorType) {
        this.majorType = majorType == null ? null : majorType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zgk_university_enrolling_algorithm.real_enrolled
     *
     * @return the value of zgk_university_enrolling_algorithm.real_enrolled
     *
     * @mbggenerated Tue Feb 07 14:28:33 CST 2017
     */
    public String getRealEnrolled() {
        return realEnrolled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zgk_university_enrolling_algorithm.real_enrolled
     *
     * @param realEnrolled the value for zgk_university_enrolling_algorithm.real_enrolled
     *
     * @mbggenerated Tue Feb 07 14:28:33 CST 2017
     */
    public void setRealEnrolled(String realEnrolled) {
        this.realEnrolled = realEnrolled == null ? null : realEnrolled.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zgk_university_enrolling_algorithm.high_score
     *
     * @return the value of zgk_university_enrolling_algorithm.high_score
     *
     * @mbggenerated Tue Feb 07 14:28:33 CST 2017
     */
    public String getHighScore() {
        return highScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zgk_university_enrolling_algorithm.high_score
     *
     * @param highScore the value for zgk_university_enrolling_algorithm.high_score
     *
     * @mbggenerated Tue Feb 07 14:28:33 CST 2017
     */
    public void setHighScore(String highScore) {
        this.highScore = highScore == null ? null : highScore.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zgk_university_enrolling_algorithm.high_rank
     *
     * @return the value of zgk_university_enrolling_algorithm.high_rank
     *
     * @mbggenerated Tue Feb 07 14:28:33 CST 2017
     */
    public Integer getHighRank() {
        return highRank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zgk_university_enrolling_algorithm.high_rank
     *
     * @param highRank the value for zgk_university_enrolling_algorithm.high_rank
     *
     * @mbggenerated Tue Feb 07 14:28:33 CST 2017
     */
    public void setHighRank(Integer highRank) {
        this.highRank = highRank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zgk_university_enrolling_algorithm.low_score
     *
     * @return the value of zgk_university_enrolling_algorithm.low_score
     *
     * @mbggenerated Tue Feb 07 14:28:33 CST 2017
     */
    public String getLowScore() {
        return lowScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zgk_university_enrolling_algorithm.low_score
     *
     * @param lowScore the value for zgk_university_enrolling_algorithm.low_score
     *
     * @mbggenerated Tue Feb 07 14:28:33 CST 2017
     */
    public void setLowScore(String lowScore) {
        this.lowScore = lowScore == null ? null : lowScore.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zgk_university_enrolling_algorithm.low_rank
     *
     * @return the value of zgk_university_enrolling_algorithm.low_rank
     *
     * @mbggenerated Tue Feb 07 14:28:33 CST 2017
     */
    public Integer getLowRank() {
        return lowRank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zgk_university_enrolling_algorithm.low_rank
     *
     * @param lowRank the value for zgk_university_enrolling_algorithm.low_rank
     *
     * @mbggenerated Tue Feb 07 14:28:33 CST 2017
     */
    public void setLowRank(Integer lowRank) {
        this.lowRank = lowRank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zgk_university_enrolling_algorithm.avg_score
     *
     * @return the value of zgk_university_enrolling_algorithm.avg_score
     *
     * @mbggenerated Tue Feb 07 14:28:33 CST 2017
     */
    public String getAvgScore() {
        return avgScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zgk_university_enrolling_algorithm.avg_score
     *
     * @param avgScore the value for zgk_university_enrolling_algorithm.avg_score
     *
     * @mbggenerated Tue Feb 07 14:28:33 CST 2017
     */
    public void setAvgScore(String avgScore) {
        this.avgScore = avgScore == null ? null : avgScore.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zgk_university_enrolling_algorithm.avg_rank
     *
     * @return the value of zgk_university_enrolling_algorithm.avg_rank
     *
     * @mbggenerated Tue Feb 07 14:28:33 CST 2017
     */
    public Integer getAvgRank() {
        return avgRank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zgk_university_enrolling_algorithm.avg_rank
     *
     * @param avgRank the value for zgk_university_enrolling_algorithm.avg_rank
     *
     * @mbggenerated Tue Feb 07 14:28:33 CST 2017
     */
    public void setAvgRank(Integer avgRank) {
        this.avgRank = avgRank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zgk_university_enrolling_algorithm.plan_enroll
     *
     * @return the value of zgk_university_enrolling_algorithm.plan_enroll
     *
     * @mbggenerated Tue Feb 07 14:28:33 CST 2017
     */
    public Integer getPlanEnroll() {
        return planEnroll;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zgk_university_enrolling_algorithm.plan_enroll
     *
     * @param planEnroll the value for zgk_university_enrolling_algorithm.plan_enroll
     *
     * @mbggenerated Tue Feb 07 14:28:33 CST 2017
     */
    public void setPlanEnroll(Integer planEnroll) {
        this.planEnroll = planEnroll;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zgk_university_enrolling_algorithm.std_high_rank
     *
     * @return the value of zgk_university_enrolling_algorithm.std_high_rank
     *
     * @mbggenerated Tue Feb 07 14:28:33 CST 2017
     */
    public Integer getStdHighRank() {
        return stdHighRank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zgk_university_enrolling_algorithm.std_high_rank
     *
     * @param stdHighRank the value for zgk_university_enrolling_algorithm.std_high_rank
     *
     * @mbggenerated Tue Feb 07 14:28:33 CST 2017
     */
    public void setStdHighRank(Integer stdHighRank) {
        this.stdHighRank = stdHighRank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zgk_university_enrolling_algorithm.std_low_rank
     *
     * @return the value of zgk_university_enrolling_algorithm.std_low_rank
     *
     * @mbggenerated Tue Feb 07 14:28:33 CST 2017
     */
    public Integer getStdLowRank() {
        return stdLowRank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zgk_university_enrolling_algorithm.std_low_rank
     *
     * @param stdLowRank the value for zgk_university_enrolling_algorithm.std_low_rank
     *
     * @mbggenerated Tue Feb 07 14:28:33 CST 2017
     */
    public void setStdLowRank(Integer stdLowRank) {
        this.stdLowRank = stdLowRank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zgk_university_enrolling_algorithm.std_avg_rank
     *
     * @return the value of zgk_university_enrolling_algorithm.std_avg_rank
     *
     * @mbggenerated Tue Feb 07 14:28:33 CST 2017
     */
    public Integer getStdAvgRank() {
        return stdAvgRank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zgk_university_enrolling_algorithm.std_avg_rank
     *
     * @param stdAvgRank the value for zgk_university_enrolling_algorithm.std_avg_rank
     *
     * @mbggenerated Tue Feb 07 14:28:33 CST 2017
     */
    public void setStdAvgRank(Integer stdAvgRank) {
        this.stdAvgRank = stdAvgRank;
    }
}