package com.thinkjoy.report.dao;
import com.thinkjoy.base.framework.BaseMapper;
import com.thinkjoy.report.entity.ZgkUniversity;

/**
 *com.wos.mapper.ZgkUniversityMapper.java
 *2017-05-03 02:40:13
 * This was class generated by ant velocity
 */
public interface ZgkUniversityMapper extends BaseMapper<ZgkUniversity,java.lang.Long> {
 
}


