package com.thinkjoy.report.dao;

import com.thinkjoy.base.framework.BaseMapper;
import com.thinkjoy.report.entity.ZgkUniversityEnrollingAlgorithm;
import com.thinkjoy.report.view.AreaView;
import com.thinkjoy.report.view.ReportAlgorithmRank;
import com.thinkjoy.report.view.StdView;
import com.thinkjoy.report.view.UpdateRankView;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Map;

/**
 *com.wos.mapper.ZgkUniversityEnrollingAlgorithmMapper.java
 *2017-02-07 02:28:33
 * This was class generated by ant velocity
 */
public interface ZgkUniversityEnrollingAlgorithmMapper extends BaseMapper<ZgkUniversityEnrollingAlgorithm,java.lang.Integer> {

    /**
     * 获取历年年份集
     * @return
     */
    List<String> selectGroupEnrollingYear();

    /**
     * 获取分组区域数据
     * @return
     */
    List<String> selectGroupEnrollingArea();

    /**
     * 总招生人数
     * @return
     */
    Integer selectRealEnrollSum(Map map);


    /**
     * 历史年份总数
     * @param map
     * @return
     */
    Integer selectEnrollYearCount(Map map);

    /**
     * 院校ID列表
     * @return
     */
    List<String> selectUniversityIdGroup();

    /**
     * 往年标准排名总和
     * @param map
     * @return
     */
    ReportAlgorithmRank selectHistorySumRank(Map map);

    /**
     * 往年标准排名 标准差
     * @param map
     * @return
     */
    ReportAlgorithmRank selectHistoryStdRank(Map map);


    List<AreaView> selectEnrollYearCountByUid(Map map);

    List<StdView> selectHistorySumRankByUid(Map map);
    /**
     * 批量更新rank
     * @param updateRankViews
     * @return
     */
    Integer updateRank(@Param("rankList") List<UpdateRankView> updateRankViews);

    Integer updateStdRank(List<ZgkUniversityEnrollingAlgorithm> zgkUniversityEnrollingAlgorithms);
}


