package com.thinkjoy.report.dao;

import com.thinkjoy.base.framework.BaseMapper;
import com.thinkjoy.report.entity.ZgkUniversityEnrolling;

import java.util.List;

/**
 *com.wos.mapper.ZgkUniversityEnrollingMapper.java
 *2017-05-03 03:10:16
 * This was class generated by ant velocity
 */
public interface ZgkUniversityEnrollingMapper extends BaseMapper<ZgkUniversityEnrolling,java.lang.Long> {

    Integer insertUniversityEnrollingList(List<ZgkUniversityEnrolling> zgkUniversityEnrollingList);

}


